version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: lost_and_found_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lost_and_found_data
      MYSQL_DATABASE: LostAndFondDatabase
      # MYSQL_USER: root
      # MYSQL_PASSWORD: lost_and_found_data
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql-data:
